# Northstar — one-shot installer (PowerShell)
#
# Usage:
#   iwr -useb https://raw.githubusercontent.com/brayden/northstar/main/scripts/install.ps1 | iex
#
# Same flow as scripts/install.sh, adapted for PowerShell + Docker Desktop.

$ErrorActionPreference = "Stop"

$Repo = if ($env:NORTHSTAR_REPO) { $env:NORTHSTAR_REPO } else { "brayden/northstar" }
$Ref  = if ($env:NORTHSTAR_REF)  { $env:NORTHSTAR_REF }  else { "main" }
$Root = if ($env:NORTHSTAR_HOME) { $env:NORTHSTAR_HOME } else { Join-Path $HOME ".northstar" }
$Raw  = "https://raw.githubusercontent.com/$Repo/$Ref"

function Step($msg)  { Write-Host "  ▶ $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Die($msg)   { Write-Host "  ✗ $msg" -ForegroundColor Red; exit 1 }

Write-Host "Northstar installer — repo: $Repo@$Ref" -ForegroundColor Green
Write-Host ""

# 1. Preflight
try { docker version | Out-Null } catch { Die "Docker is required. Install Docker Desktop." }
try { docker compose version | Out-Null } catch { Die "Docker Compose v2 is required." }

# 2. Provision
Step "Provisioning $Root\"
New-Item -ItemType Directory -Force -Path $Root, "$Root\data", "$Root\backups" | Out-Null

function Fetch($src, $dest) {
  if (Test-Path $dest) { Step "exists $(Split-Path -Leaf $dest) — leaving as-is"; return }
  Invoke-WebRequest -UseBasicParsing -Uri "$Raw/$src" -OutFile $dest
  Step "wrote   $(Split-Path -Leaf $dest)"
}

Fetch "infra/docker-compose.yml" "$Root\docker-compose.yml"
Fetch "server/.env.example"      "$Root\.env"
try   { Fetch "infra/litestream.yml" "$Root\litestream.yml" }
catch { Warn "litestream.yml not fetched — backups disabled" }
Fetch "scripts/uninstall.ps1"    "$Root\uninstall.ps1"

# 3. Master passphrase
$envContent = Get-Content $Root\.env -ErrorAction SilentlyContinue
if (-not ($envContent | Select-String -Quiet '^NORTHSTAR_MASTER_PASSPHRASE=')) {
  $bytes = New-Object byte[] 30
  (New-Object System.Security.Cryptography.RNGCryptoServiceProvider).GetBytes($bytes)
  $pass = [Convert]::ToBase64String($bytes) -replace '[/+=]', '_'
  Add-Content -Path $Root\.env -Value "`n# Generated by installer — do not share`nNORTHSTAR_MASTER_PASSPHRASE=$pass"
  Step "generated master passphrase"
} else {
  Step "exists master passphrase — reusing"
}

# Admin token (gates pair/initiate)
$adminLine = $envContent | Select-String '^NORTHSTAR_ADMIN_TOKEN=(.+)$' | Select-Object -First 1
if ($adminLine) {
  $adminToken = $adminLine.Matches[0].Groups[1].Value
  Step "exists admin token — reusing"
} else {
  $tbytes = New-Object byte[] 36
  (New-Object System.Security.Cryptography.RNGCryptoServiceProvider).GetBytes($tbytes)
  $adminToken = ([Convert]::ToBase64String($tbytes) -replace '[/+=]', '')
  $lines = Get-Content $Root\.env
  if ($lines | Select-String -Quiet '^NORTHSTAR_ADMIN_TOKEN=') {
    $lines = $lines | ForEach-Object {
      if ($_ -match '^NORTHSTAR_ADMIN_TOKEN=') { "NORTHSTAR_ADMIN_TOKEN=$adminToken" } else { $_ }
    }
    Set-Content -Path $Root\.env -Value $lines -Encoding utf8
  } else {
    Add-Content -Path $Root\.env -Value "NORTHSTAR_ADMIN_TOKEN=$adminToken"
  }
  Step "generated admin token"
}

# 4. Boot
Step "Pulling images ..."
Push-Location $Root
try {
  docker compose pull *>$null
  Step "Booting compose stack ..."
  docker compose up -d | Out-Null
} finally {
  Pop-Location
}

# 5. Wait for API
Step "Waiting for /api/health ..."
$ok = $false
for ($i = 0; $i -lt 30; $i++) {
  try {
    Invoke-RestMethod -Uri "http://localhost:8080/api/health" -TimeoutSec 2 | Out-Null
    $ok = $true; break
  } catch { Start-Sleep -Seconds 1 }
}
if (-not $ok) { Warn "Server didn't answer on :8080 within 30s. Check  docker compose logs server"; exit 1 }

# 6. Mint pairing code (using the admin token)
$pair = Invoke-RestMethod -Uri "http://localhost:8080/api/pair/initiate" -Method POST -Body "{}" `
  -ContentType "application/json" `
  -Headers @{ "Authorization" = "Bearer $adminToken" }
$pairCode = $pair.code

# 7. LAN IP best-effort
$lanIp = (Get-NetIPAddress -AddressFamily IPv4 -PrefixOrigin Dhcp -ErrorAction SilentlyContinue | Select-Object -First 1).IPAddress
if (-not $lanIp) { $lanIp = "<server-ip>" }

Write-Host ""
Write-Host "✓ Northstar is up." -ForegroundColor Green
Write-Host ""
Write-Host "  Server URL : http://${lanIp}:8080"
Write-Host "  Pair code  : $pairCode  (valid 10 minutes)" -ForegroundColor Green
Write-Host ""
Write-Host "  Pair from the iOS app:"
Write-Host "    Server: http://${lanIp}:8080"
Write-Host "    Code:   $pairCode"
Write-Host ""
Write-Host "  Useful commands:"
Write-Host "    cd $Root; docker compose logs -f server"
Write-Host "    cd $Root; docker compose down              # stop everything"
Write-Host "    & $Root\uninstall.ps1                       # remove (prompts to keep/wipe data)"
Write-Host ""
Write-Host "  Docs: https://github.com/$Repo#readme"
