#!/usr/bin/env bash
#
# Northstar — one-shot installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/builtbybrayden/northstar/main/scripts/install.sh | bash
#
# What it does:
#   1. Verifies Docker + Docker Compose are available.
#   2. Creates ~/.northstar/ and seeds compose + env from the GitHub release.
#   3. Generates a random master passphrase if one isn't set.
#   4. Boots the stack in mock mode.
#   5. Mints a pairing code and prints the URL the iOS app should hit.
#
# Idempotent — running it twice updates the compose file and reuses the existing
# data volume and passphrase.

set -euo pipefail

REPO="${NORTHSTAR_REPO:-builtbybrayden/northstar}"
REF="${NORTHSTAR_REF:-main}"
ROOT="${NORTHSTAR_HOME:-$HOME/.northstar}"
RAW="https://raw.githubusercontent.com/${REPO}/${REF}"

c_red()   { printf "\033[31m%s\033[0m" "$*"; }
c_grn()   { printf "\033[32m%s\033[0m" "$*"; }
c_yel()   { printf "\033[33m%s\033[0m" "$*"; }
c_dim()   { printf "\033[2m%s\033[0m" "$*"; }

step() { echo "  $(c_grn "▶") $*"; }
warn() { echo "  $(c_yel "!") $*" >&2; }
die()  { echo "  $(c_red "✗") $*" >&2; exit 1; }

# 1. Preflight
echo "$(c_grn "Northstar installer") — repo: ${REPO}@${REF}"
echo

command -v docker >/dev/null 2>&1 || die "Docker is required. Install from https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (\`docker compose\`, not \`docker-compose\`)."
command -v curl >/dev/null 2>&1 || die "curl is required."

# 2. Seed ~/.northstar/
step "Provisioning $ROOT/"
mkdir -p "$ROOT"/{data,backups}

fetch() {
  local src="$1" dest="$2"
  if [[ -f "$dest" ]]; then
    step "$(c_dim "exists") $(basename "$dest") — leaving as-is"
    return
  fi
  curl -fsSL "$RAW/$src" -o "$dest"
  step "wrote   $(basename "$dest")"
}

fetch "infra/docker-compose.yml" "$ROOT/docker-compose.yml"
fetch "server/.env.example"      "$ROOT/.env"
fetch "infra/litestream.yml"     "$ROOT/litestream.yml" || warn "litestream.yml not fetched — backups disabled"
fetch "scripts/uninstall.sh"     "$ROOT/uninstall.sh"
chmod +x "$ROOT/uninstall.sh" || true

# 3. Master passphrase
if ! grep -q '^NORTHSTAR_MASTER_PASSPHRASE=' "$ROOT/.env"; then
  PASS="$(LC_ALL=C tr -dc 'A-Za-z0-9_-' </dev/urandom | head -c 40 || true)"
  printf "\n# Generated by installer — do not share\nNORTHSTAR_MASTER_PASSPHRASE=%s\n" "$PASS" >> "$ROOT/.env"
  step "generated master passphrase"
else
  step "$(c_dim "exists") master passphrase — reusing"
fi

# 3b. Admin token (gates pair/initiate)
if grep -qE '^NORTHSTAR_ADMIN_TOKEN=.+' "$ROOT/.env"; then
  ADMIN_TOKEN="$(grep -E '^NORTHSTAR_ADMIN_TOKEN=' "$ROOT/.env" | head -n1 | cut -d= -f2-)"
  step "$(c_dim "exists") admin token — reusing"
else
  ADMIN_TOKEN="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48 || true)"
  # Overwrite (or append) the line — handle both empty and missing.
  if grep -q '^NORTHSTAR_ADMIN_TOKEN=' "$ROOT/.env"; then
    # macOS sed -i needs '' arg; GNU sed doesn't. Use a temp file for portability.
    awk -v t="$ADMIN_TOKEN" '/^NORTHSTAR_ADMIN_TOKEN=/{print "NORTHSTAR_ADMIN_TOKEN=" t; next} {print}' "$ROOT/.env" > "$ROOT/.env.new"
    mv "$ROOT/.env.new" "$ROOT/.env"
  else
    printf "NORTHSTAR_ADMIN_TOKEN=%s\n" "$ADMIN_TOKEN" >> "$ROOT/.env"
  fi
  step "generated admin token"
fi

# 4. Boot
step "Pulling images …"
( cd "$ROOT" && docker compose pull ) >/dev/null

step "Booting compose stack …"
( cd "$ROOT" && docker compose up -d )

# 5. Wait for the API to come up
step "Waiting for /api/health …"
for _ in $(seq 1 30); do
  if curl -fsS http://localhost:8080/api/health >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

if ! curl -fsS http://localhost:8080/api/health >/dev/null 2>&1; then
  warn "Server didn't answer on :8080 within 30s. Check  docker compose logs server"
  exit 1
fi

# 6. Mint a pairing code (using the admin token we just generated/found)
PAIR_RESP="$(curl -fsS -X POST http://localhost:8080/api/pair/initiate \
  -H "Authorization: Bearer $ADMIN_TOKEN" \
  -d '{}')"
PAIR_CODE="$(echo "$PAIR_RESP" | grep -oE '"code":"[0-9]+"' | head -n1 | sed -E 's/.*"([0-9]+)".*/\1/')"

# 7. Best-effort LAN IP (Linux ip route → macOS route)
LAN_IP="$( (ip route get 1.1.1.1 2>/dev/null | awk '/src/ {print $7; exit}') || true)"
[[ -z "${LAN_IP:-}" ]] && LAN_IP="$( (route get default 2>/dev/null | awk '/interface:/ {print $2; exit}' | xargs -I{} ifconfig {} 2>/dev/null | awk '/inet / {print $2; exit}') || true)"
[[ -z "${LAN_IP:-}" ]] && LAN_IP="<server-ip>"

echo
echo "$(c_grn "✓ Northstar is up.")"
echo
echo "  Server URL : http://$LAN_IP:8080"
echo "  Pair code  : $(c_grn "$PAIR_CODE")  (valid 10 minutes)"
echo
echo "  Pair from the iOS app:"
echo "    Server: http://$LAN_IP:8080"
echo "    Code:   $PAIR_CODE"
echo
echo "  Useful commands:"
echo "    cd $ROOT && docker compose logs -f server"
echo "    cd $ROOT && docker compose down              # stop everything"
echo "    bash $ROOT/uninstall.sh                      # remove (prompts to keep/wipe data)"
echo
echo "  Docs: https://github.com/${REPO}#readme"
